[package]
name = "grove"
version = "0.1.0"
authors = ["Alex Tomberg <a.tomberg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
